src/Entity/Transaction.php
<?php

declare(strict_types=1);

/*
 * (c) Jeroen van den Enden <info@endroid.nl>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Endroid\FinanceBundle\Entity;

class Transaction
{
    private $date;
    private $description;
    private $amount;

    public function __construct(\DateTime $date, string $description, float $amount)
    {
        $this->date = $date;
        $this->description = $description;
        $this->amount = $amount;
    }

    public function getDate(): \DateTime
    {
        return $this->date;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function getAmount(): float
    {
        return $this->amount;
    }
}

src/Entity/TransactionCollection.php
<?php

declare(strict_types=1);

/*
 * (c) Jeroen van den Enden <info@endroid.nl>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Endroid\FinanceBundle\Entity;

class TransactionCollection
{
    private $transactions;

    public function __construct()
    {
        $this->transactions = [];
    }

    public function add(Transaction $transaction): void
    {
        $this->transactions[] = $transaction;
    }

    public function getIterator(): \Iterator
    {
        foreach ($this->transactions as $transaction) {
            yield $transaction;
        }
    }

    public function getTotal(): float
    {
        $total = 0;

        foreach ($this->transactions as $transaction) {
            $total += $transaction->getAmount();
        }

        return $total;
    }
}

src/Controller/DashboardController.php
<?php

declare(strict_types=1);

/*
 * (c) Jeroen van den Enden <info@endroid.nl>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Endroid\FinanceBundle\Controller;

use Endroid\FinanceBundle\Loader\IngPdfLoader;
use Endroid\FinanceBundle\Splitter\CategorySplitter;
use Endroid\FinanceBundle\Splitter\MonthSplitter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Twig\Environment;

class DashboardController
{
    private $loader;
    private $categorySplitter;
    private $monthSplitter;
    private $renderer;

    public function __construct(
        IngPdfLoader $loader,
        CategorySplitter $categorySplitter,
        MonthSplitter $monthSplitter,
        Environment $renderer
    ) {
        $this->loader = $loader;
        $this->categorySplitter = $categorySplitter;
        $this->monthSplitter = $monthSplitter;
        $this->renderer = $renderer;
    }

    public function __invoke(Request $request): Response
    {
        $transactions = [];

        if ($request->files->has('file')) {
            $transactions = $this->loader->load($request->files->get('file')->getPathname());
            $transactions = $this->categorySplitter->split($transactions);
            foreach ($transactions as $categoryLabel => &$categoryTransactions) {
                $categoryTransactions = $this->monthSplitter->split($categoryTransactions);
            }
        }

        return new Response($this->renderer->render('@EndroidFinance/dashboard.html.twig', [
            'transactions' => $transactions,
        ]));
    }
}

src/Resources/views/dashboard.html.twig
{% extends '@EndroidFinance/layout.html.twig' %}

{% block title %}Finance - {{ parent() }}{% endblock %}

{% block content %}

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js" type="text/javascript"></script>

    <h1>Finance</h1>

    {% for category, categoryTransactions in transactions %}

        <h2>{{ category }}</h2>

        <canvas id="category_{{ loop.index }}"></canvas>
        <script>
            var category_{{ loop.index }}_data = {
                labels : ["{{ categoryTransactions|keys|join("\",\"")|raw }}"],
                datasets : [
                    {
                        fillColor : "rgba(172,194,255,0.4)",
                        strokeColor : "#ACC29D",
                        pointColor : "#fff",
                        pointStrokeColor : "#9DB89D",
                        data : [{% for transactions in categoryTransactions %}"{{ transactions.total }}"{% if not loop.last %},{% endif %}{% endfor %}]
                    }
                ]
            };
            var category_{{ loop.index }} = document.getElementById('category_{{ loop.index }}').getContext('2d');
			new Chart(category_{{ loop.index }}, { type: 'line', data: category_{{ loop.index }}_data });
        </script>
        <br /><br />

        <table class="table table-striped invoice-table">
            <tbody>
                {% for month, monthTransactions in categoryTransactions %}
                    <tr>
                        <td width="80px">{{ month }}</td>
                        <td>
                            <a href="#" onclick="$('#transactions_{{ loop.index }}_{{ loop.parent.loop.index }}').toggle(); return false;">Details</a>
                            <table id="transactions_{{ loop.index }}_{{ loop.parent.loop.index }}" >
                                {% for transaction in monthTransactions.iterator %}
                                    <tr>
                                        <td>{{ transaction.date|date('Y-m-d') }}</td>
                                        <td>{{ transaction.description }}</td>
                                        <td></td>
                                        <td align="right">{{ transaction.amount }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </td>
                        <td width="80px" align="right">{{ monthTransactions.total }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <br />

    {% endfor %}

    <form action="{{ path('finance_dashboard') }}" method="post" enctype="multipart/form-data">
        <p>
            <label for="file">Select a file</label> <input type="file" name="file" id="file"> <br />
            <button>Upload File</button>
        <p>
    </form>

{% endblock %}

src/Resources/views/layout.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Finance{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ preload(asset('/build/base.css', 'endroid_finance')) }}">
    {% endblock %}
</head>
<body>
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <main class="col-sm-12 col-md-12 pt-3" role="main">
                {% block content %}

                {% endblock %}
            </main>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ preload(asset('/build/manifest.js', 'endroid_finance')) }}"></script>
    <script src="{{ preload(asset('/build/base.js', 'endroid_finance')) }}"></script>
{% endblock %}
</body>
</html>